-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 21:32:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gorillablog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gorillablog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gorillablog` DEFAULT CHARACTER SET utf8 ;
USE `gorillablog` ;

-- -----------------------------------------------------
-- Table `gorillablog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorillablog`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorillablog`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorillablog`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorillablog`.`article_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorillablog`.`article_categories` (
  `article_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `category_id`),
  INDEX `fk_articles_has_categories_categories1_idx` (`category_id` ASC),
  INDEX `fk_articles_has_categories_articles_idx` (`article_id` ASC),
  CONSTRAINT `fk_articles_has_categories_articles`
    FOREIGN KEY (`article_id`)
    REFERENCES `gorillablog`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `gorillablog`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
